name: Deploy Website Infrastructure

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: terraform_project

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHubActionsTerraform

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Initialize
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var="bucket_name=${BUCKET_NAME}"