name: Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-24.04

    defaults:
      run:
        working-directory: terraform_project

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.15.5

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Terraform format check
        run: terraform fmt -check -diff

      - name: Terraform initialize
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan
      
      - name: Terraform apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve

      - name: Upload Files to S3 Bucket
        run: |
          aws s3 cp ./website/index.html s3://${{ secrets.BUCKET_NAME }}/index.html --delete
          aws s3 cp ./website/script.js s3://${{ secrets.BUCKET_NAME }}/script.js --delete
          aws s3 cp ./website/style.css s3://${{ secrets.BUCKET_NAME }}/style.css --delete
          aws s3 cp --recursive assets/ s3://${{ secrets.BUCKET_NAME }}/ --delete
          